### ISSUE TITLE
Can't load the project on my local machine

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/ibn-battuta-new#1]
It gets to the load project screen (studio background but no top bar) with this message in the console:
```
Uncaught (in promise) Error: Error pulling. Might be due to a conflict!
    at GitShellResource.GitShellResource_pullRepo_ (git-client-resource.js:204:23)
    at async Function.Project_loadProject_ (project.js:842:19)
    at async LivelyWorld.LivelyWorld_initializeStudio_ (world.js:661:19)
    at async eval (world.js:572:17)
```

**Comment by rickmcgeer** [comment]
I had fixed a typo in https://github.com/engageLively/ibn-battuta-new/blob/main/ui/intro.cp.js, line 279:
`src: projectAsset('ibn NEW MAP VIDEO 2.mp4'),`
There is no such file, so I corrected it to:
`src: projectAsset('Ibn NEW MAP VIDEO 2.mp4'),`

I did this under a branch `bug-fix` to keep it clean (I was going to do a PR) and since this seems to bet a git problem I thought that might be the issue.  but, amazingly, it seems to be clean, and the line seems to have reverted to lower case.

```
rick@LAPTOP-I4KMLV6U:~/lively.next/local_projects/engageLively--ibn-battuta-new$ git status
On branch bug-fix
nothing to commit, working tree clean
rick@LAPTOP-I4KMLV6U:~/lively.next/local_projects/engageLively--ibn-battuta-new$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
rick@LAPTOP-I4KMLV6U:~/lively.next/local_projects/engageLively--ibn-battuta-new$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
rick@LAPTOP-I4KMLV6U:~/lively.next/local_projects/engageLively--ibn-battuta-new$ git pull
Already up to date.
rick@LAPTOP-I4KMLV6U:~/lively.next/local_projects/engageLively--ibn-battuta-new$
```

**Comment by rickmcgeer** [comment]
I blew away the directory and then re-initialized it, which cleared up the problem

**Comment by rickmcgeer** [comment]
Cleared it
